"""Add ativo field to Cliente

Revision ID: b294f9dc25ef
Revises: 
Create Date: 2025-01-08 12:38:07.690071

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'b294f9dc25ef'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('mensagens',
    sa.Column('id_mensagem', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('id_cliente', sa.Integer(), nullable=False),
    sa.Column('data_envio', sa.Date(), nullable=False),
    sa.Column('conteudo', sa.Text(), nullable=False),
    sa.Column('tipo', sa.String(length=50), nullable=True),
    sa.ForeignKeyConstraint(['id_cliente'], ['clientes.id_cliente'], ),
    sa.PrimaryKeyConstraint('id_mensagem')
    )
    op.alter_column('cliente_treinos', 'id_cliente',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=False)
    op.alter_column('cliente_treinos', 'id_treino',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=False)
    op.drop_index('idx_cliente_treino', table_name='cliente_treinos')
    op.add_column('clientes', sa.Column('ativo', sa.Boolean(), nullable=True))
    op.alter_column('medidas', 'id_cliente',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=False)
    op.drop_index('idx_medidas_cliente', table_name='medidas')
    op.drop_index('idx_medidas_cliente_data', table_name='medidas')
    op.alter_column('pagamentos', 'id_cliente',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=False)
    op.drop_index('idx_pagamentos_cliente', table_name='pagamentos')
    op.alter_column('treino_exercicios', 'id_treino',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=False)
    op.alter_column('treino_exercicios', 'id_exercicio',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=False)
    op.drop_index('idx_exercicio_treino', table_name='treino_exercicios')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('idx_exercicio_treino', 'treino_exercicios', ['id_treino', 'id_exercicio'], unique=False)
    op.alter_column('treino_exercicios', 'id_exercicio',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=True)
    op.alter_column('treino_exercicios', 'id_treino',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=True)
    op.create_index('idx_pagamentos_cliente', 'pagamentos', ['id_cliente'], unique=False)
    op.alter_column('pagamentos', 'id_cliente',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=True)
    op.create_index('idx_medidas_cliente_data', 'medidas', ['id_cliente', 'data_medicao'], unique=False)
    op.create_index('idx_medidas_cliente', 'medidas', ['id_cliente'], unique=False)
    op.alter_column('medidas', 'id_cliente',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=True)
    op.drop_column('clientes', 'ativo')
    op.create_index('idx_cliente_treino', 'cliente_treinos', ['id_cliente', 'id_treino'], unique=False)
    op.alter_column('cliente_treinos', 'id_treino',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=True)
    op.alter_column('cliente_treinos', 'id_cliente',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=True)
    op.drop_table('mensagens')
    # ### end Alembic commands ###
